services:
  entropy_core:
    build: backend/core/.
    image: entropy/core:latest
    container_name: entropy-core
    env_file: backend/core/env_var
    volumes:
      - ./backend/core:/app
      - ./backend/logs:/core/logs
    ports:
      - 8000:8000
    networks:
      - entropy
    restart: "on-failure"

  entropy_db:
    image: postgres:12-alpine
    container_name: entropy-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/postgres/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - entropy
    restart: "on-failure"

  entropy_ui:
    build: demo_ui/.
    image: entropy/ui:latest
    container_name: entropy-ui
    environment:
      - BASE_URL=ws://entropy_core:8000
      - CORE_URL=http://entropy_core:8000
    volumes:
      - ./demo_ui:/app
    ports:
      - 8501:8501
    networks:
      - entropy
    restart: "on-failure"

networks:
  entropy:
    name: entropy-network
